# budujemy z apline
FROM openjdk:8-jdk-alpine
# kopiowanie z target do obrazu
COPY ./config-server/target/config-server-0.0.1-SNAPSHOT.jar  config-server.jar
# uruchomienie jar'a, opcja dla szypszego startu Tomcata
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/config-server.jar"]
