---

server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-secondary:8762/eureka
  instance:
    hostname: eureka-primary
spring:
  profiles: eureka-primary

---

server:
  port: 8762
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-primary:8761/eureka
  instance:
    hostname: eureka-secondary
spring:
  profiles: eureka-secondary