eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8761/eureka/, http://eureka-secondary:8762/eureka/
---
spring:
  profiles: polite
  application:
    name: decision-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8000
---
spring:
  profiles: rough
  application:
    name: decision-service
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8001